module.exports = {
    PREFIX: '!',
    PORT: process.env.PORT || 3000,
	BRANCH_TEST: process.env.BRANCH_TEST || false,

    DISCORD_TOKEN: process.env.DISCORD_TOKEN,
    MONGO_URI: process.env.MONGO_URI,
    GROQ_API_KEY: process.env.GROQ_API_KEY,

    DEV_USER_ID: '1314033520460693635',
    LEVEL_CHANNEL_ID: '1511569329949380668',

    MARKET_BOARD_CHANNEL_ID: process.env.MARKET_BOARD_CHANNEL_ID,
    VIP_ROLE_ID: process.env.VIP_ROLE_ID,
    MUTE_ROLE_ID: process.env.MUTE_ROLE_ID,
    STREAM_PING_ROLE_ID: process.env.STREAM_PING_ROLE_ID,
    SR_MEMBER_ROLE_ID: process.env.SR_MEMBER_ROLE_ID,

    CHAT_INCOME: 5,
    CASINO_COOLDOWN: 30000,

    VIP_PRICE: 75000,
    BOOSTER_PRICE: 35000,
    COLOR_PRICE: 50000,
    ORACLE_PRICE: 25000,
    TITLE_PRICE: 40000,
    SHIELD_PRICE: 15000
};
